name: mm-local-development

services:
  host:
    container_name: mm.host
    image: ${DOCKER_REGISTRY-}host
    restart: "no"
    build:
      context: .
      dockerfile: src/Host/Dockerfile
    networks:
      - local_shared_network
    ports:
      - "5001:5001"
    depends_on:
      - mm.postgres
      # - mm.rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - DatabaseOptions__ConnectionString=Server=mm.postgres;Port=5432;Database=modular-monolith-db;User Id=postgres;Password=postgres;Include Error Detail=true
      - EventBusOptions__UseInMemoryEventBus=true
      - ObservabilityOptions__AppVersion=1.0.0
      - ObservabilityOptions__OtlpLoggingEndpoint=http://mm.seq/ingest/otlp/v1/logs
      - ObservabilityOptions__OtlpLoggingProtocol=HttpProtobuf
      - ObservabilityOptions__LogGeneratedSqlQueries=true
      - ObservabilityOptions__EnableMetrics=true
      - ObservabilityOptions__OtlpMetricsUsePrometheusDirectly=true
      # - ObservabilityOptions__OtlpMetricsEndpoint=http://mm.otel-collector:4317
      # - ObservabilityOptions__OtlpMetricsProtocol=Grpc
      - ObservabilityOptions__EnableTracing=true
      - ObservabilityOptions__OtlpTracingEndpoint=http://mm.jaeger:4317
      - ObservabilityOptions__OtlpTracingProtocol=Grpc
      - JwtOptions__AccessTokenExpirationInMinutes=1440
      - CachingOptions__UseRedis=false
      - CachingOptions__Redis__Host=mm.redis
      - CachingOptions__Redis__Port=6379
      - CachingOptions__Redis__Password=admin
      - CachingOptions__Redis__AppName=modular-monolith-

  mm.postgres:
    container_name: mm.postgres
    image: postgres:latest
    restart: "no"
    volumes:
      - ./.containers/mm.postgres:/var/lib/postgresql/data
    networks:
      - local_shared_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # mm.redis:
  #   image: redis/redis-stack:latest
  #   container_name: mm.redis
  #   restart: "no"
  #   volumes:
  #     - ./.containers/mm.redis:/data
  #   networks:
  #     - local_shared_network
  #   ports:
  #     - 6379:6379
  #     - 8001:8001
  #   environment:
  #     - REDIS_PASSWORD=admin
  #   command: redis-server --requirepass admin

  mm.jaeger:
    container_name: mm.jaeger
    image: jaegertracing/all-in-one:latest
    restart: "no"
    networks:
      - local_shared_network
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
      - "4317:4317" # OTLP gRPC receiver for jaeger
      - "4318:4318"
    volumes:
      - ./.containers/mm.jaeger/data:/badger/data
      - ./.containers/mm.jaeger/wal:/badger/wal

  mm.prometheus:
    container_name: mm.prometheus
    image: prom/prometheus
    restart: "no"
    networks:
      - local_shared_network
    ports:
      - "9090:9090"
    volumes:
      - ./.containers/mm.prometheus:/prometheus
      - ./observability/prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

  mm.postgres-exporter:
    container_name: mm.postgres-exporter
    image: prometheuscommunity/postgres-exporter
    restart: "no"
    networks:
      - local_shared_network
    ports:
      - "9187:9187"  # Expose PostgreSQL exporter metrics
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@mm.postgres:5432/postgres?sslmode=disable

  mm.grafana:
    container_name: mm.grafana
    image: grafana/grafana
    restart: "no"
    networks:
      - local_shared_network
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/mm.grafana:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
      # - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - mm.prometheus

#  mm.otel-collector:
#    image: otel/opentelemetry-collector-contrib:latest
#    container_name: mm.otel-collector
#    networks:
#      - local_shared_network
#    ports:
#      - "4317:4317" # OTLP gRPC receiver
#      - "4318:4318" # OTLP HTTP receiver"
#      - "9464:9464" # Prometheus exporter port
#    volumes:
#      - ./observability/otel-collector-config.yml:/etc/otel-collector-config.yml
#    command: ["--config=/etc/otel-collector-config.yml"]

  mm.seq:
    image: datalust/seq:latest
    container_name: mm.seq
    restart: "no"
    networks:
      - local_shared_network
    ports:
      - "5341:80"
    volumes:
      - ./.containers/mm.seq:/data
    environment:
      - ACCEPT_EULA=Y

  mm.kafka:
    container_name: mm.kafka
    image: docker.io/bitnami/kafka:3.9
    restart: unless-stopped
    networks:
      - local_shared_network
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - ./.containers/mm.kafka:/bitnami
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@mm.kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  mm.kafka-ui:
    container_name: mm.kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    networks:
      - local_shared_network
    ports:
      - "8080:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true

  mm.debezium:
    container_name: mm.debezium
    image: debezium/connect:2.7.3.Final
    depends_on:
      - mm.kafka
      - mm.postgres
    networks:
      - local_shared_network
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: mm.kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

networks:
  local_shared_network:
    external: true
