version: '3.4'
name: mm-local-development

services:
  host:
    image: ${DOCKER_REGISTRY-}host
    container_name: mm.host
    build:
      context: .
      dockerfile: src/Host/Dockerfile
    ports:
      - 8080:8080
    environment:
      - DatabaseOptions__ConnectionString=Server=mm.database;Port=5432;Database=modular-monolith-db;User Id=postgres;Password=postgres;Include Error Detail=true
      - CustomLoggingOptions__SeqUrl=http://mm.seq:5341
      - MessageBrokerOptions__Host=mm.rabbitmq
      - MessageBrokerOptions__Port=5672
      - MessageBrokerOptions__Username=guest
      - MessageBrokerOptions__Password=guest 

  mm.database:
    image: postgres:latest
    container_name: mm.database
    volumes:
      - ./.containers/mm.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  mm.rabbitmq:
    image: rabbitmq:3-management
    container_name: mm.rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.containers/mm.rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mm.seq:
    image: datalust/seq:latest
    container_name: mm.seq
    ports:
      - 5341:80
    volumes:
      - ./.containers/mm.seq:/data
    environment:
      - ACCEPT_EULA=Y
