# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
version: '3.9'
name: modular-monolith-ddd-vsa

services:
  webapi:
    image: baranacikgoz/webapi:placeholder #version will be written by CI/CD
    container_name: webapi
    ports:
      - 5000:5000
    env_file:
      - .env
    # environment: # Better come from .env file
    #   - ASPNETCORE_ENVIRONMENT=Production
    #   - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16
    container_name: postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:2023.4
    container_name: seq
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq:/data

volumes:
  postgresql:
  seq:
