version: '3.4'
name: mm-local-development

services:
  host:
    image: ${DOCKER_REGISTRY-}host
    container_name: mm.host
    restart: "no"
    build:
      context: .
      dockerfile: src/Host/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mm.database
      # - mm.rabbitmq
    environment:
      - DatabaseOptions__ConnectionString=Server=mm.database;Port=5432;Database=modular-monolith-db;User Id=postgres;Password=postgres;Include Error Detail=true
      - EventBusOptions__UseInMemoryEventBus=true
      - OutboxOptions__BackgroundJobPeriodInSeconds=5
      - OutboxOptions__BatchSizePerExecution=100
      - OutboxOptions__MaxFailCountBeforeSentToDeadLetter=3
      - LoggingMonitoringTracingOptions__SeqUrl=http://mm.seq:80
      - LoggingMonitoringTracingOptions__EnableMetric=false
      - LoggingMonitoringTracingOptions__EnableTracing=false
      - LoggingMonitoringTracingOptions__OtlpTracingEndpoint=http://mm.seq:80/ingest/otlp/v1/traces
      - JwtOptions__AccessTokenExpirationInMinutes=1440 

  mm.database:
    image: postgres:latest
    container_name: mm.database
    restart: "no"
    volumes:
      - ./.containers/mm.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # mm.rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: mm.rabbitmq
  #   restart: "no"
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #     - ./.containers/mm.rabbitmq:/var/lib/rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest

  mm.seq:
    image: datalust/seq:latest
    container_name: mm.seq
    restart: "no"
    ports:
      - 5341:80
    volumes:
      - ./.containers/mm.seq:/data
    environment:
      - ACCEPT_EULA=Y
