<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.Endpoints\Common.Endpoints.csproj"/>
    <ProjectReference Include="..\Inventory.Application\Inventory.Application.csproj"/>
    <ProjectReference Include="..\Inventory.Infrastructure\Inventory.Infrastructure.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
