DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'IAM') THEN
        CREATE SCHEMA "IAM";
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS "IAM"."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'IAM') THEN
            CREATE SCHEMA "IAM";
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."EventStoreEvents" (
        "AggregateId" uuid NOT NULL,
        "Version" bigint NOT NULL,
        "AggregateType" character varying(128) NOT NULL,
        "EventType" character varying(256) NOT NULL,
        "Event" jsonb NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "LastModifiedOn" timestamp with time zone,
        "LastModifiedBy" uuid,
        CONSTRAINT "PK_EventStoreEvents" PRIMARY KEY ("AggregateId", "Version")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."Roles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."Users" (
        "Id" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "LastModifiedOn" timestamp with time zone,
        "LastModifiedBy" uuid,
        "Name" character varying(50) NOT NULL,
        "LastName" character varying(50) NOT NULL,
        "NationalIdentityNumber" character varying(11) NOT NULL,
        "BirthDate" date NOT NULL,
        "ImageUrl" text,
        "RefreshTokenHash" bytea NOT NULL,
        "RefreshTokenExpiresAt" timestamp with time zone NOT NULL,
        "Version" bigint NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "IAM"."Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "IAM"."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "IAM"."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."UserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "IAM"."Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "IAM"."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE TABLE "IAM"."UserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "IAM"."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE INDEX "IX_EventStoreEvents_AggregateType" ON "IAM"."EventStoreEvents" ("AggregateType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE INDEX "IX_RoleClaims_RoleId" ON "IAM"."RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "IAM"."Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE INDEX "IX_UserClaims_UserId" ON "IAM"."UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE INDEX "IX_UserLogins_UserId" ON "IAM"."UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON "IAM"."UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE INDEX "EmailIndex" ON "IAM"."Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE UNIQUE INDEX "IX_Users_NationalIdentityNumber" ON "IAM"."Users" ("NationalIdentityNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE INDEX "IX_Users_RefreshTokenHash" ON "IAM"."Users" ("RefreshTokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "IAM"."Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100535_Initial') THEN
    INSERT INTO "IAM"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260403100535_Initial', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260405140955_AddFullTextSearch') THEN
    ALTER TABLE "IAM"."Users" ADD "SearchVector" tsvector GENERATED ALWAYS AS (to_tsvector('english', "Name" || ' ' || "LastName")) STORED;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260405140955_AddFullTextSearch') THEN
    CREATE INDEX "IX_Users_SearchVector" ON "IAM"."Users" USING GIN ("SearchVector");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260405140955_AddFullTextSearch') THEN
    INSERT INTO "IAM"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260405140955_AddFullTextSearch', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260407125227_RenameEventStoreEventsToAuditLog') THEN
    ALTER TABLE "IAM"."EventStoreEvents" RENAME TO "AuditLog";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260407125227_RenameEventStoreEventsToAuditLog') THEN
    ALTER TABLE "IAM"."AuditLog" RENAME CONSTRAINT "PK_EventStoreEvents" TO "PK_AuditLog";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260407125227_RenameEventStoreEventsToAuditLog') THEN
    DROP INDEX "IAM"."IX_EventStoreEvents_AggregateType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260407125227_RenameEventStoreEventsToAuditLog') THEN
    CREATE INDEX "IX_AuditLog_AggregateId_AggregateType_CreatedOn" ON "IAM"."AuditLog" ("AggregateId", "AggregateType", "CreatedOn" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260407125227_RenameEventStoreEventsToAuditLog') THEN
    INSERT INTO "IAM"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260407125227_RenameEventStoreEventsToAuditLog', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    DROP INDEX "IAM"."IX_Users_SearchVector";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    ALTER TABLE "IAM"."Users" DROP COLUMN "SearchVector";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    ALTER TABLE "IAM"."Users" ADD "FullName" character varying(100) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    ALTER TABLE "IAM"."Users" ADD COLUMN "SearchVector" tsvector NULL GENERATED ALWAYS AS (to_tsvector('english'::regconfig, COALESCE("FullName", ''))) STORED;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    CREATE INDEX "IX_Users_SearchVector" ON "IAM"."Users" USING GIN ("SearchVector");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    DROP INDEX "IAM"."IX_Users_NationalIdentityNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    ALTER TABLE "IAM"."Users" DROP COLUMN "NationalIdentityNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    ALTER TABLE "IAM"."Users" DROP COLUMN "LastName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    ALTER TABLE "IAM"."Users" DROP COLUMN "Name";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260511160325_MergeNameAndLastNameIntoFullName') THEN
    INSERT INTO "IAM"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260511160325_MergeNameAndLastNameIntoFullName', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260513172507_AddPhoneNumberIndex') THEN
    CREATE INDEX "IX_Users_PhoneNumber" ON "IAM"."Users" ("PhoneNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260513172507_AddPhoneNumberIndex') THEN
    INSERT INTO "IAM"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260513172507_AddPhoneNumberIndex', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260619154607_MultilingualSearch') THEN
    CREATE EXTENSION IF NOT EXISTS unaccent;

    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'simple_unaccent') THEN
            CREATE TEXT SEARCH CONFIGURATION simple_unaccent ( COPY = simple );
            ALTER TEXT SEARCH CONFIGURATION simple_unaccent
                ALTER MAPPING FOR hword, hword_part, word WITH unaccent, simple;
        END IF;
    END $$;

    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'english_unaccent') THEN
            CREATE TEXT SEARCH CONFIGURATION english_unaccent ( COPY = english );
            ALTER TEXT SEARCH CONFIGURATION english_unaccent
                ALTER MAPPING FOR hword, hword_part, word WITH unaccent, english_stem;
        END IF;
    END $$;

    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'turkish_unaccent') THEN
            CREATE TEXT SEARCH CONFIGURATION turkish_unaccent ( COPY = turkish );
            ALTER TEXT SEARCH CONFIGURATION turkish_unaccent
                ALTER MAPPING FOR hword, hword_part, word WITH unaccent, turkish_stem;
        END IF;
    END $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260619154607_MultilingualSearch') THEN
    DROP INDEX "IAM"."IX_Users_SearchVector";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260619154607_MultilingualSearch') THEN
    ALTER TABLE "IAM"."Users" DROP COLUMN "SearchVector";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260619154607_MultilingualSearch') THEN
    ALTER TABLE "IAM"."Users" ADD COLUMN "SearchVector" tsvector GENERATED ALWAYS AS (setweight(to_tsvector('simple_unaccent', coalesce("FullName", '')), 'A')) STORED;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260619154607_MultilingualSearch') THEN
    CREATE INDEX "IX_Users_SearchVector" ON "IAM"."Users" USING GIN ("SearchVector");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260619154607_MultilingualSearch') THEN
    INSERT INTO "IAM"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260619154607_MultilingualSearch', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    DROP INDEX "IAM"."IX_Users_RefreshTokenHash";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    ALTER TABLE "IAM"."Users" DROP COLUMN "RefreshTokenExpiresAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    ALTER TABLE "IAM"."Users" DROP COLUMN "RefreshTokenHash";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    CREATE TABLE "IAM"."Sessions" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "DeviceId" uuid NOT NULL,
        "ClientId" character varying(50) NOT NULL,
        "DeviceName" character varying(100),
        "LastUsedAt" timestamp with time zone NOT NULL,
        "LastIp" text,
        "LastUserAgent" text,
        "AbsoluteExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "RevokedReason" text,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "LastModifiedOn" timestamp with time zone,
        "LastModifiedBy" uuid,
        CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "IAM"."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    CREATE TABLE "IAM"."RefreshTokens" (
        "Id" uuid NOT NULL,
        "SessionId" uuid NOT NULL,
        "TokenHash" bytea NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "ConsumedAt" timestamp with time zone,
        "ReplacedByTokenId" uuid,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "LastModifiedOn" timestamp with time zone,
        "LastModifiedBy" uuid,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Sessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "IAM"."Sessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    CREATE INDEX "IX_RefreshTokens_SessionId" ON "IAM"."RefreshTokens" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    CREATE INDEX "IX_RefreshTokens_TokenHash" ON "IAM"."RefreshTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    CREATE UNIQUE INDEX "IX_Sessions_UserId_DeviceId_ClientId" ON "IAM"."Sessions" ("UserId", "DeviceId", "ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "IAM"."__EFMigrationsHistory" WHERE "MigrationId" = '20260710081830_AddSessionsAndRefreshTokens') THEN
    INSERT INTO "IAM"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260710081830_AddSessionsAndRefreshTokens', '10.0.9');
    END IF;
END $EF$;
COMMIT;

