DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Outbox') THEN
        CREATE SCHEMA "Outbox";
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS "Outbox"."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "Outbox"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100652_Initial') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Outbox') THEN
            CREATE SCHEMA "Outbox";
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "Outbox"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100652_Initial') THEN
    CREATE TABLE "Outbox"."OutboxMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CreatedOn" timestamp with time zone NOT NULL,
        "Event" text NOT NULL,
        "IsProcessed" boolean NOT NULL,
        "ProcessedOn" timestamp with time zone,
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "Outbox"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100652_Initial') THEN
    CREATE INDEX "IX_OutboxMessages_CreatedOn_IsProcessed" ON "Outbox"."OutboxMessages" ("CreatedOn", "IsProcessed");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "Outbox"."__EFMigrationsHistory" WHERE "MigrationId" = '20260403100652_Initial') THEN
    INSERT INTO "Outbox"."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260403100652_Initial', '10.0.1');
    END IF;
END $EF$;
COMMIT;

