#!/usr/bin/env bash
# Migration drift guard.
#
# Two artifacts exist per EF migration:
#   1. the C# migration (in each module's Infrastructure/Persistence/Migrations) — the app's model
#   2. the committed idempotent SQL (migrations/<Module>/*.sql) — what the deploy sidecar applies
#
# They are generated by SEPARATE manual commands (`make ef-add-*` then `make ef-script-*`). If a
# dev runs the first and forgets the second, the model gains a migration with no SQL to apply →
# the sidecar silently no-ops → prod schema drifts behind the code → app crashes on the missing
# column. The sidecar cannot catch this (it runs whatever SQL is committed).
#
# This guard fails CI when any migration present in a module's model has no committed .sql file
# carrying its 14-digit MigrationId. Run locally with `make check-migration-drift`.
#
# Module DbContexts are only registered when the module is active (config-driven, Setup.Modules.cs).
# TestModuleOverride=* forces loadAll so every context resolves at design time — otherwise disabled
# modules (e.g. Products) would error and be silently skipped.
set -euo pipefail

cd "$(dirname "$0")/.."
export TestModuleOverride='*'

# module : infrastructure project : DbContext  (mirrors the ef-script-* Makefile targets)
MODULES="
IAM:src/Modules/IAM/IAM.Infrastructure:IAMDbContext
Products:src/Modules/Products/Products.Infrastructure:ProductsDbContext
Outbox:src/Modules/Outbox/Outbox:OutboxDbContext
"

# dotnet-ef is not in .config/dotnet-tools.json — install a local tool on demand (no-op if present).
if ! dotnet ef --version >/dev/null 2>&1; then
  echo "installing dotnet-ef local tool..."
  dotnet tool install dotnet-ef >/dev/null 2>&1 || dotnet tool update dotnet-ef >/dev/null 2>&1
fi

drift=0

# Coverage self-check: any module directory with its own DbContext must be listed in $MODULES
# above. Without this, adding a new module (with a DbContext) but forgetting to wire it into this
# hardcoded list means the guard silently never checks it.
listed_mods=$(printf '%s\n' "$MODULES" | grep -oE '^[A-Za-z]+' || true)
while IFS= read -r ctx_file; do
  mod=$(printf '%s\n' "$ctx_file" | cut -d/ -f3)
  if ! printf '%s\n' "$listed_mods" | grep -qxF "$mod"; then
    echo "  ERROR: module '$mod' has a DbContext ($ctx_file) but is not listed in \$MODULES in this script."
    echo "         Add it to check-migration-drift.sh MODULES and the ef-script-* Makefile targets before merging."
    drift=1
  fi
done < <(find src/Modules -name '*DbContext.cs' -not -path '*.Application/*')

for entry in $MODULES; do
  mod=${entry%%:*}; rest=${entry#*:}
  project=${rest%%:*}; context=${rest#*:}
  dir="migrations/$mod"

  echo "== $mod =="

  # Capture combined output + exit code. A non-zero exit means the model could not be read
  # (e.g. DbContext failed to resolve) — that MUST fail the guard, never be treated as "0 migrations".
  if ! out=$(dotnet ef migrations list \
        --project "$project" \
        --startup-project src/Host/Host \
        --context "$context" \
        --no-connect 2>&1); then
    echo "$out" | tail -15
    echo "  ERROR: 'dotnet ef migrations list' failed for $context — cannot verify drift."
    exit 1
  fi

  # MigrationIds the app's model expects (14-digit timestamp + name), one per line. Serilog/build
  # noise in $out does not start with 14 digits, so it is filtered out.
  model_ids=$(printf '%s\n' "$out" | grep -oE '^[0-9]{14}_[A-Za-z0-9_]+' || true)

  if [ -z "$model_ids" ]; then
    echo "  no migrations in model"
    continue
  fi

  for id in $model_ids; do
    if [ -d "$dir" ] && grep -rqlF "$id" "$dir"/*.sql 2>/dev/null; then
      echo "  ok   $id"
    else
      echo "  MISS $id — no committed SQL in $dir/ (run: make ef-script-$mod to=$id)"
      drift=1
    fi
  done
done

if [ "$drift" -ne 0 ]; then
  echo ""
  echo "DRIFT: model has migrations with no committed SQL script. The deploy sidecar would not"
  echo "apply them. Generate the missing script(s) above and commit migrations/."
  exit 1
fi

echo ""
echo "no drift — every model migration has a committed SQL script."
