name: cd

on:
  push:
    branches:
      - 'release/*'
      - 'hotfix/*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Webapi image tag (leave empty to use branch/tag name)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Version from Branch or Tag Name
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            REF_NAME=${GITHUB_REF#refs/*/}
            VERSION=${REF_NAME#*/}
          else
            VERSION=${{ github.event.inputs.tag }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          file: src/Host/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapi:${{ env.VERSION }}

      # - name: Change image tag in docker-compose file
      #   run: |
      #     VERSION=${{ env.VERSION }}
      #     sed -i "s/webapi:placeholder/webapi:$VERSION/" docker-compose.yml

      # - name: Copy docker-compose file to Server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_SSH_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     source: "docker-compose.yml"
      #     target: "~/backend"

      # - name: Deploy on Production Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_SSH_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd path-to-docker-compose-file
      #       sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      #       sudo docker compose pull webapi
      #       sudo docker compose up -d --no-deps webapi
